#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Text.RegularExpressions;

namespace SISPro
{
/// <summary>
/// Custom-text path (no Firmata): generates a profile plus a matching Arduino sketch
/// and a random-value mock sketch.
///
/// Digital inputs start at pin 2 (FirstDigitalPin). Pins 0 and 1 are the USB serial
/// link (RX/TX) on Uno/Nano/Mega-class boards, so reading them returns serial traffic,
/// not a button.
///
/// The profile is written with explicit digitalPins/analogChannels, so its Input
/// System layout comes from SerialDeviceLayoutRegistry at edit time - the same path
/// Set Up Arduino uses. No C# device class is generated any more: pin-numbered
/// controls (D2, D3, ...) can't be expressed by the old digitalCount/analogCount
/// (D0..Dn) convention, and a compiled class with the same layout name would fight
/// the registry's layout. Classes generated by older versions keep working.
/// </summary>
public class SerialDeviceCodeGenerator : EditorWindow
{
    const int FirstDigitalPin = 2;       // 0/1 = USB serial RX/TX
    const int UnoMaxDigitalInputs = 12;  // pins 2..13
    const int UnoMaxAnalogInputs = 6;    // A0..A5 (A6/A7 exist on Nano/Mega only)

    string deviceName = "Uno";
    int digitalCount = 8;    // D2-D9
    int analogCount = 6;     // A0-A5
    string baseFolder = "Assets/SISPro/GeneratedDevices";

    [MenuItem("Tools/SISPro/Advanced/Generate Custom Sketch + Profile", priority = 101)]
    public static void Init()
    {
        GetWindow<SerialDeviceCodeGenerator>("Sketch Generator").Show();
    }

    void OnGUI()
    {
        GUILayout.Label("Custom Arduino Sketch + Profile Generator", EditorStyles.boldLabel);
        deviceName = EditorGUILayout.TextField("Device Name", deviceName);
        digitalCount = Mathf.Max(0, EditorGUILayout.IntField("Digital Inputs", digitalCount));
        analogCount = Mathf.Max(0, EditorGUILayout.IntField("Analog Inputs", analogCount));
        baseFolder = EditorGUILayout.TextField("Base Folder", baseFolder);

        if (digitalCount > 0)
            EditorGUILayout.LabelField(
                $"Digital pins used: D{FirstDigitalPin}-D{FirstDigitalPin + digitalCount - 1} (0/1 are the USB serial link)",
                EditorStyles.miniLabel);

        if (digitalCount > UnoMaxDigitalInputs)
            EditorGUILayout.HelpBox(
                $"An Uno/Nano only has digital pins {FirstDigitalPin}-13 ({UnoMaxDigitalInputs} inputs). " +
                "More than that needs a Mega (or use the analog pins).", MessageType.Warning);

        if (analogCount > UnoMaxAnalogInputs)
            EditorGUILayout.HelpBox(
                $"A{UnoMaxAnalogInputs} and above don't exist on an Uno - the sketch won't compile for it. " +
                "Nano (A6/A7) and Mega (A0-A15) are fine.", MessageType.Warning);

        if (digitalCount == 0 && analogCount == 0)
            EditorGUILayout.HelpBox("Add at least one input.", MessageType.Info);

        using (new EditorGUI.DisabledScope(digitalCount == 0 && analogCount == 0))
        {
            if (GUILayout.Button("Generate and Save"))
                Generate();
        }
    }

    void Generate()
    {
        if (string.IsNullOrWhiteSpace(deviceName))
        {
            deviceName = "UnnamedDevice";
            Debug.LogWarning("Device name was empty — defaulting to 'UnnamedDevice'.");
        }

        string folderRoot = baseFolder.Replace('\\', '/').TrimEnd('/');
        string sanitizedDeviceName = SanitizeDeviceName(deviceName);
        string uniqueName = GetUniqueDeviceName(folderRoot, sanitizedDeviceName);

        var digitalPins = new List<int>();
        for (int i = 0; i < digitalCount; i++) digitalPins.Add(FirstDigitalPin + i);
        var analogChannels = new List<int>();
        for (int i = 0; i < analogCount; i++) analogChannels.Add(i);

        // Arduino IDE requires <name>/<name>.ino, which deviceFolder/uniqueName.ino satisfies.
        string deviceFolder = folderRoot + "/" + uniqueName;
        string testerFolder = deviceFolder + "/Tester";
        Directory.CreateDirectory(deviceFolder);
        Directory.CreateDirectory(testerFolder);

        string inoPath = $"{deviceFolder}/{uniqueName}.ino";
        File.WriteAllText(inoPath, GenerateArduinoSketch(uniqueName, digitalPins, analogChannels));

        string mockSketchName = $"{uniqueName}Mock";
        string mockSketchFolder = $"{testerFolder}/{mockSketchName}";
        Directory.CreateDirectory(mockSketchFolder);
        string mockPath = $"{mockSketchFolder}/{mockSketchName}.ino";
        File.WriteAllText(mockPath, GenerateMockArduinoSketch(uniqueName, digitalPins, analogChannels));

        AssetDatabase.Refresh(); // folders must be known to the AssetDatabase before CreateAsset

        string profilePath = $"{deviceFolder}/{uniqueName}Profile.asset";
        string relativePath = profilePath.StartsWith(Application.dataPath)
            ? "Assets" + profilePath.Substring(Application.dataPath.Length)
            : profilePath;

        var profile = ScriptableObject.CreateInstance<SerialDeviceProfile>();
        profile.deviceID = uniqueName;
        profile.layoutName = uniqueName + "InputDevice";
        profile.transport = SerialTransport.CustomText;
        profile.baudRate = 115200;          // matches Serial.begin() in the sketch
        profile.digitalActiveLow = true;    // sketch uses INPUT_PULLUP: pressed reads 0
        profile.digitalPins = digitalPins;
        profile.analogChannels = analogChannels;
        profile.analogMaxValue = 1023;      // 10-bit ADC on Uno/Nano/Mega
        profile.digitalCount = digitalCount;  // informational only once pin lists are set
        profile.analogCount = analogCount;

        AssetDatabase.CreateAsset(profile, relativePath);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        // CreateAsset doesn't run OnValidate - register the layout so the Input
        // Actions binding picker sees the device right away.
        SerialDeviceLayoutRegistry.EnsureRegistered(profile);

        Debug.Log($"[CodeGen] Created device profile at {relativePath}");
        Debug.Log($"Generated Arduino sketch: {inoPath}");
        Debug.Log($"Generated MOCK Arduino sketch: {mockPath}");

        EditorGUIUtility.PingObject(profile);
    }

    static string SanitizeDeviceName(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
            input = "UnnamedDevice";

        string cleaned = Regex.Replace(input.Trim(), "[^a-zA-Z0-9_]", "_");
        if (string.IsNullOrWhiteSpace(cleaned.Trim('_')))
            return "UnnamedDevice";

        // Layout and control names must not start with a digit.
        if (char.IsDigit(cleaned[0]))
            cleaned = "Device_" + cleaned;

        return cleaned;
    }

    static string GetUniqueDeviceName(string folderRoot, string baseName)
    {
        int counter = 1;
        string name = baseName;

        while (Directory.Exists(folderRoot + "/" + name))
        {
            counter++;
            name = $"{baseName}{counter}";
        }

        return name;
    }

    static string GenerateArduinoSketch(string deviceName, List<int> digitalPins, List<int> analogChannels)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine($"// === {deviceName}.ino ===");
        sb.AppendLine("// Auto-generated Arduino sketch: REAL INPUTS");
        sb.AppendLine("// Digital pins use INPUT_PULLUP: wire each button between the pin and GND.");
        sb.AppendLine("// A pressed button reads 0; Unity treats that as pressed because the");
        sb.AppendLine("// profile's 'Digital Active Low' is on.");
        sb.AppendLine("// Pins 0 and 1 are left alone - they carry the USB serial link.");
        sb.AppendLine();
        sb.AppendLine("void setup() {");
        foreach (var pin in digitalPins)
            sb.AppendLine($"  pinMode({pin}, INPUT_PULLUP);");
        sb.AppendLine("  Serial.begin(115200);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("void loop() {");
        sb.AppendLine("  String line = \"\";");

        foreach (var pin in digitalPins)
            sb.AppendLine($"  line += \"D{pin}:\" + String(digitalRead({pin})) + \";\";");

        foreach (var ch in analogChannels)
            sb.AppendLine($"  line += \"A{ch}:\" + String(analogRead(A{ch})) + \";\";");

        sb.AppendLine("  Serial.println(line);");
        sb.AppendLine("  delay(10);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    static string GenerateMockArduinoSketch(string deviceName, List<int> digitalPins, List<int> analogChannels)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine($"// === {deviceName}Mock.ino ===");
        sb.AppendLine("// Auto-generated Arduino sketch: RANDOM TEST INPUTS (no wiring needed)");
        sb.AppendLine();
        sb.AppendLine("void setup() {");
        sb.AppendLine("  Serial.begin(115200);");
        sb.AppendLine("  randomSeed(analogRead(0));");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("void loop() {");
        sb.AppendLine("  String line = \"\";");

        foreach (var pin in digitalPins)
            sb.AppendLine($"  line += \"D{pin}:\" + String(random(0, 2)) + \";\";");

        foreach (var ch in analogChannels)
            sb.AppendLine($"  line += \"A{ch}:\" + String(random(0, 1024)) + \";\";");

        sb.AppendLine("  Serial.println(line);");
        sb.AppendLine("  delay(1000);");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
}
#endif